"""fix relationship

Revision ID: 2bea010987a5
Revises: 98484f2afc63
Create Date: 2025-12-04 08:34:24.599262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bea010987a5'
down_revision = '98484f2afc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_addresses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_addresses_user_id'))

    # ### end Alembic commands ###
