"""Unique fields

Revision ID: 90999d56888f
Revises: 0785193382f7
Create Date: 2025-12-02 14:51:17.886664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90999d56888f'
down_revision = '0785193382f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
