"""Initial migration.

Revision ID: a2dd172c8fde
Revises: 
Create Date: 2025-09-12 09:41:05.536766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dd172c8fde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello_world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('greeting', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hello_world')
    # ### end Alembic commands ###
